FROM microsoft/aspnet:1.0.0-rc1-final-coreclr

EXPOSE 5003
ENTRYPOINT ["dnx", "web"]

WORKDIR /app/MusicStore.Models
COPY MusicStore.Models/project.json .
RUN dnu restore

ADD MusicStore.Models/ ./
RUN dnu build

WORKDIR /app/MusicStore.ProductsCatalogService
COPY MusicStore.ProductsCatalogService/project.json .
RUN dnu restore

ADD MusicStore.ProductsCatalogService/ ./
RUN dnu build