version: '2'

networks:
  musicstore_network:
    driver: overlay
    
services:
  store:
    image: 'jcorioland/musicstore-front:1.1'
    ports:
      - "80:5000"
    networks:
      - musicstore_network
    container_name: store

  checkout:
    image: 'jcorioland/musicstore-checkout:1.1'
    ports:
      - 5004
    networks:
      - musicstore_network
    container_name: checkout

  catalog:
    image: 'jcorioland/musicstore-catalog:1.1'
    ports:
      - 5003
    networks:
      - musicstore_network
    container_name: catalog