version: '2'
services:
  store:
    image: 'jcorioland/musicstore-front:latest'
    ports:
      - "80:5000"
    networks:
      - musicstore_network
    container_name: store

  checkout:
    image: 'jcorioland/musicstore-checkout:latest'
    ports:
      - 5004
    networks:
      - musicstore_network
    container_name: checkout

  catalog:
    image: 'jcorioland/musicstore-catalog:latest'
    ports:
      - 5003
    networks:
      - musicstore_network
    container_name: catalog
   
networks:
  musicstore_network:
    driver: overlay