FROM microsoft/aspnet:1.0.0-rc1-update1-coreclr

EXPOSE 5003
ENTRYPOINT ["dnx", "web"]

ADD MusicStore.Models ./app/MusicStore.Models
ADD MusicStore.ProductsCatalogService/ ./app/MusicStore.ProductsCatalogService

WORKDIR /app/MusicStore.Models
RUN dnu restore

WORKDIR /app/MusicStore.ProductsCatalogService
RUN dnu restore