FROM microsoft/aspnet:1.0.0-rc1-update1-coreclr

EXPOSE 5004
ENTRYPOINT ["dnx", "web"]

ADD MusicStore.Models/ ./app/MusicStore.Models
ADD MusicStore.CheckoutService/ ./app/MusicStore.CheckoutService

WORKDIR /app/MusicStore.Models
RUN dnu restore

WORKDIR /app/MusicStore.CheckoutService
RUN dnu restore