FROM microsoft/aspnet:1.0.0-rc1-update1-coreclr

EXPOSE 5000
ENTRYPOINT ["dnx", "web"]

ADD MusicStore.Models/ ./app/MusicStore.Models
ADD MusicStore/ ./app/MusicStore

WORKDIR /app/MusicStore.Models
RUN dnu restore

WORKDIR /app/MusicStore
RUN dnu restore