store:
  build: .
  dockerfile: Dockerfile.store
  ports:
    - "80:5000"
  links:
    - catalog
    - checkout
  environment:
    ASPNET_ENV: Development
    
checkout:
  build: .
  dockerfile: Dockerfile.checkout
  ports:
    - "5004:5004"
  environment:
    ASPNET_ENV: Development
    
catalog:
  build: .
  dockerfile: Dockerfile.catalog
  ports:
    - "5003:5003"
  environment:
    ASPNET_ENV: Development